# Generated by Django 2.2.9 on 2020-01-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demotest', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
    ]
